export const ADD_STUDENT  = "ADD STUDENT";
export const ADD_NOTICE = "ADD NOTICE";
export const EDIT_STUDENT = "EDIT STUDENT";
export const SEARCH_STUDENT = "SEARCH STUDENT";
export const SHOW_STUDENTS = "SHOW STUDENTS";
export const COMPLAINTS = "STUDENT COMPLAINTS";
